[workspace]
resolver = "2"
members = ["wasm/background", "wasm/front"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
wasm-bindgen = "0.2.84"
web-sys = { version = "0.3.61", features = ['console'] }
